export const dataLanguage = {
  arabic: {
    header: ["الصفحة الرئيسية", "حول", "المنتجات", "اتصل", "تسجيل الدخول", "لوحة القيادة", "تسجيل الخروج"],
    hero: ["التصنيع","أنابيب الفولاذ المقاوم للصدأ","لماذا فابريتوب ؟","اكتشف الفرق.","محترف","ميسور التكلفة","ضمان الرضا","شهادة YC"],
    product: ["منتجاتنا", "طلب المنتج"],
    about: ["جودة الفولاذ المقاوم للصدأ","خصائص الفولاذ المقاوم للصدأ","فابريتوب المغرب هي شركة ملتزمة بالتميز في مجال الفولاذ المقاوم للصدأ. مهمتنا هي توفير منتجات عالية الجودة من الفولاذ المقاوم للصدأ لعملائنا بأسعار ميسورة. بفضل خبرتنا التقنية والتزامنا بالجودة، نقدم حلولًا مبتكرة ومخصصة، مدعومة بخدمة عملاء استثنائية. كل منتج نقدمه هو نتيجة لعمليات تصنيع صارمة واختيار دقيق للمواد، مما يضمن المتانة والأداء. نحن نسعى جاهدين لتجاوز توقعات عملائنا.", "كيف يعمل مع فابريتوب؟", "1- اختر منتجاتك", "2- اطلب عرض سعر", "3- قم بدفع فواتيرك بواسطة الشيك أو البطاقة أو التحويل المصرفي", "4- استلم طلبك"],
    footer: ["فابريتوب المغرب","التزامنا بالجودة. خبرتنا في الفولاذ المقاوم للصدأ. خدمة استثنائية. مهمتنا هي توفير منتجات عالية الجودة من الفولاذ المقاوم للصدأ بأسعار معقولة.","اتصل بنا","العنوان: فابريتوب (جماعة الساحل، المنطقة الصناعية، السوالم، الدار البيضاء)","الهاتف: 0526161600 / 0522638481","البريد الإلكتروني: b.fabritubemaroc@gmail.com","ساعات العمل: من الاثنين إلى الجمعة: من الساعة 8:00 صباحًا حتى الساعة 6:30 مساءً السبت: من الساعة 8:00 صباحًا حتى الساعة 01:00 مساءً","أرسل لنا رسالة","© 2024 بواسطة فابريتوب المغرب. تم إنشاؤه بفخر من قبل فابريتوب المغرب."],
    dashBoard: ["الطلبات الجديدة غير المعروضة","الطلبات المعروضة ولكن غير الموثقة","الطلبات غير الموثقة","الطلبات الموثقة","عرض الاتصالات","عرض الطلب"],
    dashBoardMenu: ["تأكيد الطلب","هذا هو طلب من","رقم الطلب","وقت الشحن","الاسم الأول والاسم الأخير","عنوان البريد الإلكتروني","الهاتف","تعليق","الإجراءات"],
    order: ["الاسم الأول","الاسم الأخير","الهاتف","تعليقات حول طلبك","لقد قرأت وأوافق على الشروط والأحكام العامة *","لوريم إيبسوم دولار سيت أميت كونسيكتيتور أديبيسيسينغ إليت. إكسبكتوري كو إنيم بلانديتيس كوام فولوبتاتوم سيكي! أسبيرناتور مينما إيكي إيوس إكسبكتوري سيت إستي أومنيس ناتوس سابيينتي كواس إليجيندي فوغا إيبسوم موليستياي موليتي في إيلوم فولوبتاس نوبيس نوستروم نيهيل فيليت ديستينكتي كوربتي ألياس، آي دي، مودي إنيم. ريروم هيك ماجني كوم كوارات كومك إست ناتوس فاكير موليستياي ديجنيزيموس! دولوريبوس تيمبوري كوام آي دي؟ أتكوي تيمبوريبوس موليستياي كوم فيليت بيتاي كواس مودي أركيتكتو نيسي فولوبتاتيبوس ماكسيما، ديستينكتي ريبليندوس ليبرو ماجني آت أومنيس ديسيرونت ماجنام ديجنيزيموس إنسيدنت تينتور أوديت كونسيكوينتور تيمبورا سيفي فيريتاتيس كواد؟ أبريام، ريبليندوس إيوس راتيون كواسي بلاسيت إيت نوستروم، إيوس ألياس هيك أومنيس ديلينتي مايوريس لاودانتيوم، ناتوس كيوبيديتاتي تيمبورا أوفيكيس. سيت ديستينكتي ديليكتوس فيليت بوسسيموس إمبيديت كوي إيروم تينتور أديبسي! أركيتكتو ألياس نام سينت ديبيتيز نوستروم آب، بورو كواي إيوس نوبيس! أميت ديسيرونت سيكي فيريتاتيس كواس تيمبوريبوس أوديو، كوام إنفينتوري، نوبيس كولبا آي دي دوتشيموس كوارات إرور تيمبورا ليبرو إيسي. سيد ماكسيما دولوريم، ديسيرونت بلانديتيس موليتي مينما ديجنيزيموس إيكي برايسينتيوم كونسيكوينتور إيوستو إيلو إكس أوبتيو! أميت نون ألياس كيسكوام إيبسا آب، إيت آي دي فولوبتاس، فيليت مودي راتيون سيت أوفيكيس. ديلينتي إنسيدنت ألياس ريبلات. سيت أوند أوديت سولاتا ديسيرونت بورو سيكي بوسسيموس ماجنام إكسبيديتا، تيمبوري نوستروم ماكسيما إيتاكوي ديلينتي موليستياي تيمبورا كواد مايوريس. فينيام، موليستياي؟", "اطلب الآن"]
  },
  french: {
    header: ["Accueil","À propos","Produit","Contact","Connexion","Dashboard","Logout"],
    hero: ["Fabrication","des tubes d'acier inoxydable","Pourquoi Fabritube ?","Découvrez la difference.","PROFESSIONNEL","ABORDABLE","SATISFACTION GARANTIE","CERTIFICATION YC"],
    product: ["Nos produits", "Commander un produit"],
    about: ["Qualité Inox","Qualité Inoxydable","FabritubeMaroc est une entreprise dédiée à l'excellence dans le domaine de l'acier inoxydable. Notre mission est de fournir à nos clients des produits d'acier inoxydable de haute qualité à des prix abordables. Forts de notre expertise technique et de notre engagement envers la qualité, nous offrons des solutions innovantes et personnalisées, soutenues par un service client exceptionnel. Chaque produit que nous livrons est le résultat de processus de fabrication rigoureux et d'une sélection minutieuse des matériaux, assurant ainsi durabilité et performance. Nous nous efforçons de dépasser les attentes de nos clients.","Comment ça fonctionne avec Fabritube ?","1-Choisissez vos produits","2-Demandez un devis","3-Réglez votre factures par chèque, carte ou virement","4-Recevez votre commande"],
    footer: ["FabritubeMaroc","Engagement envers la qualité . Expertise dans l'acier inoxydable. Service Exceptionnel . Notre mission est de fournir à nos clients des produits d'acier inoxydable de qualité à un prix abordable.","Contactez-nous","Address: fabritube (Commune Essahel, Zonne Industrielle , Soualem , Casablanca )","Phone: 0526161600 / 0522638481","Email: b.fabritubemaroc@gmail.com","Temps de travail: Lundi au Vendredi : 8:00AM à 6:30PM Samedi : 8:00AM à 01:00PM","Send Us A Message","© 2024 par FabritubeMaroc. Fièrement créé par FabritubeMaroc."],
    dashBoard: ["Nouvelles commandes non consultées","Commandes vues mais non validées","Commandes non validées","Commandes validées","Afficher les contacts","Voir la commande"],
    dashBoardMenu: ["Valider la commande","Ceci est une commande de ","Numéro de commande","Le temps pour envoye","Prénom et Nom","Email Address","Téléphone","Comment","Actions"],
    order: ["Prénom","Nom","Téléphone","Commentaires concernant votre commande","J’ai lu et j’accepte les conditions générales *","Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quo enim blanditiis quam voluptatum sequi! Aspernatur minima eaque eos excepturi sit iste omnis natus sapiente quos eligendi fuga ipsum molestiae mollitia in illum voluptas nobis nostrum nihil velit distinctio corrupti alias, id, modi enim. Rerum hic magni cum quaerat cumque est natus facere molestias dignissimos! Doloribus tempore quam id? Atque temporibus molestiae cum velit beatae quas modi architecto nisi voluptatibus maxime, distinctio repellendus libero magni at omnis deserunt magnam dignissimos incidunt tenetur odit consequuntur tempora saepe veritatis quod? Aperiam, repellendus eius ratione quasi placeat et nostrum, eos alias hic omnis deleniti maiores laudantium, natus cupiditate tempora officiis. Sit distinctio delectus velit possimus impedit qui earum tenetur adipisci! Architecto alias nam sint debitis nostrum ab, porro quia eos nobis! Amet deserunt sequi veritatis quas temporibus odio, quam inventore, nobis culpa id ducimus quaerat error tempora libero esse. Sed maxime dolorem, deserunt blanditiis mollitia minima dignissimos eaque praesentium consequuntur iusto illo ex optio! Amet non alias quisquam ipsa ab, et id voluptas, velit modi ratione sit officiis. Deleniti incidunt alias repellat. Sit unde odit soluta deserunt porro sequi possimus magnam expedita, tempore nostrum maxime itaque deleniti molestias tempora quod maiores. Veniam, molestiae?", "Commandez maintenant"]
  },
  english: {
    header: ["Home", "About", "Product", "Contact", "Login", "Dashboard", "Logout"],
    hero: ["Manufacturing", "Stainless Steel Tubes", "Why Fabritube?", "Discover the Difference", "PROFESSIONAL", "AFFORDABLE", "SATISFACTION GUARANTEED", "YC CERTIFICATION"],
    product: ["Our Products", "Order Product"],
    about: ["Stainless Steel Quality", "Stainless Steel Properties", "FabritubeMaroc is a company dedicated to excellence in the field of stainless steel. Our mission is to provide our customers with high-quality stainless steel products at affordable prices. With our technical expertise and commitment to quality, we offer innovative and personalized solutions, supported by exceptional customer service. Every product we deliver is the result of rigorous manufacturing processes and careful material selection, ensuring durability and performance. We strive to exceed our customers' expectations.", "How it Works with Fabritube?", "1- Choose your products", "2- Request a quote", "3- Pay your invoices by check, card, or bank transfer", "4- Receive your order"],
    footer: ["FabritubeMaroc", "Commitment to Quality. Expertise in Stainless Steel. Exceptional Service. Our mission is to provide our customers with quality stainless steel products at an affordable price.", "Contact Us", "Address: fabritube (Commune Essahel, Industrial Zone, Soualem, Casablanca)", "Phone: 0526161600 / 0522638481", "Email: b.fabritubemaroc@gmail.com", "Working Hours: Monday to Friday: 8:00 AM to 6:30 PM Saturday: 8:00 AM to 01:00 PM", "Send Us A Message", "© 2024 by FabritubeMaroc. Proudly created by FabritubeMaroc."],
    dashBoard: ["New orders not viewed","Orders viewed but not validated","Unvalidated orders","Validated orders","Show contacts","View order"],
    dashBoardMenu: ["Validate Order","This is an order from ","Order Number","Time to Ship","First Name and Last Name","Email Address","Phone","Comment","Actions"],
    order: ["First Name","Last Name","Phone","Comments regarding your order","I have read and accept the general terms and conditions *","Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quo enim blanditiis quam voluptatum sequi! Aspernatur minima eaque eos excepturi sit iste omnis natus sapiente quos eligendi fuga ipsum molestiae mollitia in illum voluptas nobis nostrum nihil velit distinctio corrupti alias, id, modi enim. Rerum hic magni cum quaerat cumque est natus facere molestias dignissimos! Doloribus tempore quam id? Atque temporibus molestiae cum velit beatae quas modi architecto nisi voluptatibus maxime, distinctio repellendus libero magni at omnis deserunt magnam dignissimos incidunt tenetur odit consequuntur tempora saepe veritatis quod? Aperiam, repellendus eius ratione quasi placeat et nostrum, eos alias hic omnis deleniti maiores laudantium, natus cupiditate tempora officiis. Sit distinctio delectus velit possimus impedit qui earum tenetur adipisci! Architecto alias nam sint debitis nostrum ab, porro quia eos nobis! Amet deserunt sequi veritatis quas temporibus odio, quam inventore, nobis culpa id ducimus quaerat error tempora libero esse. Sed maxime dolorem, deserunt blanditiis mollitia minima dignissimos eaque praesentium consequuntur iusto illo ex optio! Amet non alias quisquam ipsa ab, et id voluptas, velit modi ratione sit officiis. Deleniti incidunt alias repellat. Sit unde odit soluta deserunt porro sequi possimus magnam expedita, tempore nostrum maxime itaque deleniti molestias tempora quod maiores. Veniam, molestiae?", "Order now"]
  }
}